name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          pytest --disable-warnings -v

      # Step 5: Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Step 6: Authenticate Heroku CLI
      - name: Authenticate with Heroku
        run: |
          echo "Logging in to Heroku..."
          echo "$HEROKU_API_KEY" | heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Step 7: Verify Heroku login
      - name: Verify Heroku login
        run: |
          heroku auth:whoami

      # Step 8: Deploy to Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a CICD_EXAMPLE
          git push heroku HEAD:main

      # Step 9: Confirm Deployment
      - name: Confirm Deployment
        run: |
          echo "Deployment started successfully. Checking app status..."
          heroku apps:info -a CICD_EXAMPLE
